go_library(
    name = "ubuntu",
    srcs = [
        "kernel-package.go",
        "operating-system.go",
        "ubuntu-downloader.go",
    ],
    visibility = [
        "//pkg/...",
    ],
    deps = [
        "//pkg/docker",
        "//pkg/operatingsystem",
    ],
)
