go_library(
    name = "logging",
    srcs = ["logging.go"],
    visibility = [
        "//build/...",
        "//cmd/...",
        "//internal/...",
        "//pkg/...",
    ],
    deps = [
        "//third_party/go:rs_zerolog",
    ],
)
