go_library(
    name = "ghreleases",
    srcs = ["ghreleases.go"],
    visibility = [
        "//build/...",
        "//cmd/...",
    ],
    deps = [
        "//internal/logging",
        "//pkg/repository",
        "//third_party/go:google_github",
        "//third_party/go:x_oauth2",
    ],
)
