go_binary(
    name = "get-kernel-package",
    srcs = ["main.go"],
    deps = [
        "//internal/cmd",
        "//internal/logging",
        "//pkg/docker",
        "//pkg/operatingsystem",
        "//pkg/operatingsystem/resolver",
    ],
    visibility = ["PUBLIC"],
)
