go_library(
    name = "mock",
    srcs = [
        "buildid_validator.go",
        "httpclient.go",
    ],
    visibility = [
        "//pkg/operatingsystem/cos/...",
    ],
    deps = [
        "//pkg/operatingsystem/cos/buildid",
    ],
)
