go_binary(
    name = "list-kernel-packages",
    srcs = ["main.go"],
    deps = [
        "//internal/cmd",
        "//internal/logging",
        "//pkg/docker",
        "//pkg/operatingsystem",
        "//pkg/operatingsystem/resolver",
    ],
)
