go_library(
    name = "resolver",
    srcs = ["resolver.go"],
    visibility = ["//cmd/..."],
    deps = [
        "//pkg/docker",
        "//pkg/operatingsystem",
        "//pkg/operatingsystem/amazonlinux2",
    ],
)
