go_library(
    name = "operatingsystem",
    srcs = [
        "kernel-package.go",
        "operating-system.go",
    ],
    visibility = [
        "//build/...",
        "//cmd/...",
        "//pkg/...",
    ],
)
