go_binary(
    name = "release-notes",
    srcs = [
        "main.go",
        "tmpl.go",
    ],
    deps = [
        "//internal/cmd",
        "//pkg/releasenotes",
        "//pkg/repository/ghreleases",
        "//third_party/go:google_github",
    ],
)
