go_binary(
    name = "release-notes",
    srcs = [
        "main.go",
    ],
    deps = [
        "//internal/cmd",
        "//internal/logging",
        "//pkg/releasenotes",
        "//pkg/repository/ghreleases",
    ],
)
