name: release-notes
on: [workflow_dispatch]
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./pleasew build -p -v2 //cmd/release-notes
      - run: | 
         