name: release-notes
on: [workflow_dispatch]
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./pleasew run -p -v2 //cmd/release-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}