name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./pleasew build -p -v2 //...
      - run: ./pleasew -p -v2 test --detailed //...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
